20241122/w01/board/urls.py
from django.urls import path, include
from . import views

app_name = 'board'

urlpatterns = [
    path('bwrite/', views.bwrite, name='bwrite'),
    path('bview/<int:bno>', views.bview, name='bview'),
    path('breply/<int:bno>', views.breply, name='breply'),
    path('bdelete/<int:bno>', views.bdelete, name='bdelete'),
    path('bmodify/<int:bno>', views.bmodify, name='bmodify'),
    path('blist/', views.blist, name='blist'),
]

20241122/w01/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
  # 게시판 번호
  bno = models.AutoField(primary_key=True)
  id = models.CharField(max_length=100)
  # member = models.ForeignKey(Member, on_delete=models.DO_NOTHING, null=True)
  btitle = models.CharField(max_length=1000)
  bcontent = models.TextField()
  # bgroup : 답글을 사용할때 그룹
  bgroup = models.IntegerField(null=True)
  # bstep : 답글의 순서
  bstep = models.IntegerField(default=0)
  # bindent : 답글을 사용할 때 들여쓰기
  bindent = models.IntegerField(default=0)
  bhit = models.IntegerField(default=0)
  bdate = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f'{self.bno}, {self.id}, {self.btitle}, {self.bdate}'
  

20241122/w01/board/views.py
from django.shortcuts import render, redirect
from board.models import Board
from django.db.models import Max
from django.contrib import messages
from django.db.models import F

# Create your views here.
# 게시판 글 쓰기
def bwrite(request):
  if request.method == 'GET':
    return render(request, 'bwrite.html')
  else:
    id = request.POST.get('id')
    btitle = request.POST.get('btitle')
    bcontent = request.POST.get('bcontent')

    qs = Board.objects.create(id=id, btitle=btitle, bcontent=bcontent)
    qs.bgroup = qs.bno
    qs.save()
    # 1회 노출된다
    messages.success(request, message='게시글이 저장되었습니다.')
    # return redirect('board:blist')
    return render(request, 'bwrite.html', {'w_msg':'1'})

# 게시판 리스트
def blist(request):
  qs = Board.objects.all().order_by('-bgroup', 'bstep')
  context = {'blist':qs}
  return render(request, 'blist.html', context)

# 글상세보기
def bview(request, bno):
  print('게시글 번호 : ', bno)
  # 조회수 증가 filter 방식 update()
  # 여러개가 검색되면 한번에 불러와서 업데이트 가능하다.
  qs = Board.objects.filter(bno = bno)
  # F함수, 검색된 값을 가져오기
  if len(qs) < 1:
    return render(request, 'bview.html')
  qs.update(bhit=F('bhit') + 1)
  context = {'board':qs[0]}
  
  # 조회수 증가 get 방식 save 해야함
  # qs = Board.objects.get(bno = bno)
  # qs.bhit = qs.bhit + 1
  # qs.save()
  # context = {'board':qs}
  return render(request, 'bview.html', context)

# 글 수정 페이지, 글 수정 저장
def bmodify(request, bno):
  if request.method == 'GET':
    qs = Board.objects.filter(bno=bno)
    context = {'board': qs[0]}
    return render(request, 'bmodify.html', context)
  else:
    id = request.POST.get('bname')
    btitle = request.POST.get('btitle')
    bcontent = request.POST.get('bcontent')
    qs = Board.objects.get(bno = bno)
    qs.btitle = btitle
    qs.bcontent = bcontent
    qs.save()
    # return redirect('board:blist')
    return render(request, 'bmodify.html', {'u_msg':bno})

# 글 삭제
def bdelete(request, bno):
  print('게시글 번호 : ', bno)
  Board.objects.get(bno=bno).delete()
  # return redirect('board:blist')
  return render(request, 'blist.html', {'d_msg': bno})

# 답변달기
def breply(request, bno):
  if request.method == 'GET':
    print('게시글 번호 : ', bno)
    qs = Board.objects.get(bno = bno)
    return render(request, 'breply.html', {'board': qs})
  else:
    bgroup = int(request.POST.get('bgroup'))
    bstep = int(request.POST.get('bstep'))
    bindent = int(request.POST.get('bindent'))
    id = request.POST.get('id')
    btitle = request.POST.get('btitle')
    bcontent = request.POST.get('bcontent')
    # 다른 답변달기에 bstep에 1증가
    qs = Board.objects.filter(bgroup=bgroup, bstep__gt=bstep)
    qs.update(bstep = F('bstep') + 1)

    # bgroup은 부모의 bgroup을 입력
    Board.objects.create(id=id, btitle=btitle, bcontent=bcontent, bgroup=bgroup, bstep=bstep+1, bindent=bindent+1)

    print('그룹 번호 :', bgroup)
    # return redirect('board:blist')
    return render(request, 'blist.html', {'r_msg':'1'})

20241122/w01/board/templates/blist.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>
    if ('{{d_msg}}' != ''){
      alert('게시글이 삭제되었습니다.')
      location.href='/board/blist/'
    }
    if ('{{r_msg}}' != ''){
      alert('답변달기가 등록되었습니다..')
      location.href='/board/blist/'
    }
  </script>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
      <div>메시지 : {{message}}</div>
    {% endfor %}
  {% endif %}
<section>
    <h1>NOTICE</h1>
    <div class="wrapper">
      <form action="/board/search" name="search" method="post">
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
  
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      <!-- 내용부분 -->
      {%if blist%}
      {% for i in blist%}
      <tr>
        <td><span class="table-notice">{{i.bno}}</span></td>
        <td class="table-title">
          {% if i.bindent > 0%}
            {% for j in 'x'|rjust:i.bindent%}
              ▶
            {% endfor %}
          {% endif %}
        <a href="/board/bview/{{i.bno}}">{{i.btitle}}</a>
        </td>
        <td>{{i.id}}</td>
        <td>{{i.bdate|date:'Y-m-d'}}</td>
        <td>{{i.bhit}}</td>
      </tr>
      {% endfor%}
      {% else %}
      <tr>
        <td colspan='5'>데이터가 없습니다.</td>
      </tr>
      {% endif %}
    </table>

    <ul class="page-num">
      <li class="first"></li>
      <li class="prev"></li>
      <li class="num"><div>1</div></li>
      <li class="next"></li>
      <li class="last"></li>
    </ul>

    <a href="/board/bwrite"><div class="write">쓰기</div></a>
  </section>

</body>
</html>

20241122/w01/board/templates/bmodify.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글수정</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
    if ('{{u_msg}}' != ''){
      alert('게시글이 수정되었습니다.')
      location.href='/board/blist/'
      // location.href='/board/blist/{{u_msg}}/'
    }
  </script>
</head>
<body>
<section>
    <h1>게시글수정</h1>
    <hr>

    <form name="modify" method="post">
    {% comment %} <form action="{% url 'board:bmodify' board.bno%}" name="modify" method="post"> {% endcomment %}
    {% comment %} <form action="/board/bmodify/{{board.bno}}" name="modify" method="post"> {% endcomment %}
      {% csrf_token %}
      <table>
      <input type="hidden" name="bno" value="{{board.bno}}">
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="bname" value="{{board.id}}" readonly>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="btitle" value="{{board.btitle}}">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="bcontent" cols="50" rows="10">{{board.bcontent}}
            </textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">수정완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/board/blist'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

20241122/w01/board/templates/breply.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>답변달기</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    $(function(){
      $('.write').click(function(){
        if($('#btitle').val().length < 2){
          alert('제목은 2자리 이상 입력하세요')
          $('#btitle').focus()
          return flase
        }
        replyFrm.submit()
      })
    })
  </script>
</head>
<body>
<section>
    <h1>게시글수정</h1>
    <hr>

    <form action="" name="replyFrm" method="post">
      {% csrf_token %}
      <table>
      <input type="hidden" name="bno" value="{{board.bno}}">
      <input type="hidden" name="bgroup" value="{{board.bgroup}}">
      <input type="hidden" name="bstep" value="{{board.bstep}}">
      <input type="hidden" name="bindent" value="{{board.bindent}}">
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id" value='{{board.id}}'>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="btitle" id='btitle' value="<답변> {{board.btitle}}">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
<textarea name="bcontent" cols="50" rows="10">
{{board.bcontent}}
---------------------------
[답글]

</textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write">답변완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/board/bview/{{board.bno}}'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

20241122/w01/board/templates/bview.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>뷰페이지</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css' %}">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<script>
  $(function(){
    $('#deleteBtn').click(function(){
      if (confirm('{{board.bno}}번 게시글 데이터를 삭제 하시겠습니까.')){
        location.href='/board/bdelete/{{board.bno}}'
      }
    })
  });


</script>
<body>
<section>
    <h1>NOTICE</h1>

    <table>
      <colgroup>
        <col width="80%">
        <col width="10%">
        <col width="10%">
        
      </colgroup>
      <tr>
        <th colspan="3">제목</th>
      </tr>
      <tr>
        <td colspan="3"><strong>{{board.btitle}}</strong></td>
      </tr>
      <tr>
        <td>{{board.id}}</td>
        <td>조회수</td>
        <td>{{board.bhit}}</td>
      </tr>
      <tr>
        <td colspan="3" class="article">{{board.bcontent}}</td>
      </tr>
      <tr>
        <td colspan="3"><strong>다음글</strong> <span class="separator">|</span> [키즈잼] 2월 프로그램 안내</td>
      </tr>
      <tr>
        <td colspan="3"><strong>이전글</strong> <span class="separator">|</span> [키즈잼] 2020년 1분기 정기 휴관일 안내</td>
      </tr>
    </table>

    <a href="{%url 'board:blist' %}"><div class="list">목록</div></a>
    <a id='deleteBtn'><div class="list">삭제</div></a>
    {% comment %} <a href="{%url 'board:bmodify' board.bno %}"><div class="list">수정</div></a> {% endcomment %}
    <a href="/board/bmodify/{{board.bno}}"><div class="list">수정</div></a>
    <a href="/board/breply/{{board.bno}}"><div class="list">답변달기</div></a>
  </section>
</body>
</html>

20241122/w01/board/templates/bwrite.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글쓰기</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
    $(function(){
      $('.write').click(function(){
        alert('데이터 전송')
        if ($('#btitle').val().length < 2){
          alert('제목을 입력하세요.')
          $('#btitle').focus
          return false;
        }
        writeFrm.submit()
      })
    })
    if ('{{w_msg}}' != ''){
      alert('게시글이 저장되었습니다.')
      location.href='/board/blist'
    }
  </script>
</head>
<body>
<section>
    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{%url 'board:bwrite'%}" name="writeFrm" method="post">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id">
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="btitle" id='btitle'>
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="bcontent" cols="50" rows="10"></textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write">작성완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/board/blist'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

20241122/w01/board/templates/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            position: relative;
            height: 100%;
            background: #f5f6f7;
        }
        #wrap{
            position: relative;
            min-height: 100%;
            font-size: 12px;
        }
        #header{
            position: relative;
            box-sizing: border-box;
            height: 168px;
            padding: 62px 0 0;
            width: 768px;
            margin: 0 auto;
        }

        #h_logo{
            display: block;
            overflow: hidden;
            width: 231px;
            height: 44px;
            margin: 0 auto;
            font-size: 15px;
            color: transparent;
            background: url("https://static.nid.naver.com/images/ui/login/pc_sp_login_190522.png") no-repeat -1px -1px;
        }
        #container{
            padding-bottom: 50px;
            min-height: 185px;
        }
        #content{
            width: 460px;
            margin: 0 auto;
            padding-bottom: 30px;
        }
        .id_area{
            position: relative;
        }
        .input_row{
            position: relative;
            height: 29px;
            margin: 0 0 14px;
            padding: 10px 35px 10px 15px;
            border: solid 1px #dadada;
            background: #fff;
        }
        .input_box{
            display: block;
            overflow: hidden;
        }

        .int{
            font-size: 15px;
            line-height: 16px;
            position: relative;
            z-index: 9;
            width: 100%;
            height: 16px;
            padding: 7px 0 6px;
            color: #000;
            border: none;
            background: #fff;
            appearance: none;
        }
        .btn_login{
            display: block;
            width: 100%;
            height: 61px;
            margin:30px 0 14px;
            padding-top: 1px;
            border: none;
            background: #03c75a;
            text-align: center;
            color: #fff;
            font-size: 20px;
            font-weight: 700;
            line-height: 61px;
            cursor: pointer;
        }
    </style>


</head>
<body>
<div id="wrap">
    <div id="header">
        <h1>
            <a href="#" id="h_logo"></a>
        </h1>
    </div>
    <div id="container">
        <div id="content">
            <div style="margin-bottom: 7px"></div>
            <form action="naver_index2.jsp">
                <fieldset style="border: 0">
                    <div class="id_area">
                        <div class="input_row" id="id_area">
                            <span class="input_box">
                                <input type="text" name="" id="uId" class="int" placeholder="아이디">
                            </span>
                        </div>
                    </div>
                    <div class="pw_area">
                        <div class="input_row" id="pw_area">
                            <span class="input_box">
                                <input type="text" name="" id="uPw" class="int" placeholder="비밀번호">
                            </span>
                        </div>
                    </div>
                    <input class="btn_login" type="submit" value="로그인">
                </fieldset>
            </form>
        </div>
    </div>
</div>
</body>
</html>